config/routes.rb
Rails.application.routes.draw do
  get "lists/new"
  post 'lists' => 'lists#create'
  get 'lists' => 'lists#index' 
  get "/top" => 'homes#top'
  get 'lists/:id' => 'lists#show', as: 'list'
  get 'lists/:id/edit' => 'lists#edit',as: 'edit_list'
  patch 'lists/:id' => 'lists#update' ,as: 'update_list'
  delete 'lists/:id' => 'lists#destroy', as: 'destroy_list'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    # Viewへ渡すためのインスタンス変数に空のModelオブジェクトを生成する。
    @list = List.new
  end

  def create
    list = List.new(list_params)
    list.save
    redirect_to list_path(list.id)
  end

  def index
    @list = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    list = List.find(params[:id])
    list.update(list_params)
    redirect_to list_path(list.id)
  end

  def destroy
    list = List.find(params[:id])
    list.destroy
    redirect_to '/lists'
  end

  private
  def list_params
    params.require(:list).permit(:title, :body, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Sample App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>編集画面</h1>

<%= form_with model: @list, url: update_list_path(@list.id), method: :patch do |f| %>

  <h4>タイトル</h4>
  <%= f.text_field :title %>

  <h4>本文</h4>
  <%= f.text_area :body %>

  <%= f.submit '保存' %>

<% end %>

app/views/lists/index.html.erb
<h1>投稿一覧</h1>

<% @list.each do |list| %>

  <p>タイトル</p>
  <span>
    <%= link_to list.title, list_path(list.id) %>
  </span>

  <p>画像</p>
  <% if list.image.attached? %>
  <%= image_tag list.image, size: "200x200" %>
  <% else %>
  <%= image_tag 'no_image.jpg',size: "200x200" %>
  <%end%>

<% end %>

app/views/lists/new.html.erb
<h1>新規投稿</h1>
<!-- form_with部分 -->
<%= form_with model: @list, url: '/lists', method: :post do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>

  <h4>本文</h4>
  <%= f.text_area :body %>

  <h4>画像</h4>
  <%= f.file_field :image, accept: "image/*" %>

  <%= f.submit '投稿' %>

<%end%>

app/views/lists/show.html.erb
<h2>タイトル</h2>
<p><%= @list.title %></p>

<h2>本文</h2>
<p><%= @list.body %></p>

<h2>画像</h2>
<% if @list.image.attached? %>
  <%= image_tag @list.image, size: "300x300"%>
<%else%>
  <%= image_tag 'no_image.jpg',size: "300x300" %>
<%end%>

<%= link_to "編集",edit_list_path(@list.id) %>
<%= link_to "削除",destroy_list_path(@list.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>